//! tools/versioning_automation/src/issues/commands/issue_action.rs
use crate::issues::commands::{
    AssigneeLoginsOptions, AutoLinkOptions, CloseOptions, ClosureHygieneOptions, CreateOptions,
    DoneStatusOptions, ExtractRefsOptions, FetchNonComplianceReasonOptions, HasLabelOptions,
    IsRootParentOptions, IssueFieldOptions, IssueTarget, LabelExistsOptions, ListByLabelOptions,
    NeutralizeOptions, NonComplianceReasonOptions, OpenNumbersOptions, OpenSnapshotsOptions,
    ParentGuardOptions, ReadOptions, ReevaluateOptions, ReopenOnDevOptions,
    RequiredFieldsValidateOptions, StateOptions, SubissueRefsOptions, SyncProjectStatusOptions,
    TasklistRefsOptions, UpdateOptions, UpsertMarkerCommentOptions, ValidateFooterOptions,
};

#[derive(Debug, Clone)]
pub(crate) enum IssueAction {
    Help,
    Create(CreateOptions),
    Read(ReadOptions),
    DoneStatus(DoneStatusOptions),
    ReopenOnDev(ReopenOnDevOptions),
    Update(UpdateOptions),
    RepoName,
    CurrentLogin,
    IsRootParent(IsRootParentOptions),
    ValidateFooter(ValidateFooterOptions),
    Close(CloseOptions),
    Reopen(IssueTarget),
    Delete(IssueTarget),
    Reevaluate(ReevaluateOptions),
    Neutralize(NeutralizeOptions),
    AutoLink(AutoLinkOptions),
    ParentGuard(ParentGuardOptions),
    ClosureHygiene(ClosureHygieneOptions),
    RequiredFieldsValidate(RequiredFieldsValidateOptions),
    NonComplianceReason(NonComplianceReasonOptions),
    FetchNonComplianceReason(FetchNonComplianceReasonOptions),
    LabelExists(LabelExistsOptions),
    SyncProjectStatus(SyncProjectStatusOptions),
    TasklistRefs(TasklistRefsOptions),
    SubissueRefs(SubissueRefsOptions),
    UpsertMarkerComment(UpsertMarkerCommentOptions),
    OpenNumbers(OpenNumbersOptions),
    OpenSnapshots(OpenSnapshotsOptions),
    ExtractRefs(ExtractRefsOptions),
    AssigneeLogins(AssigneeLoginsOptions),
    State(StateOptions),
    HasLabel(HasLabelOptions),
    ListByLabel(ListByLabelOptions),
    Field(IssueFieldOptions),
}
