//! tools/versioning_automation/src/issues/commands/issue_action.rs
use crate::issues::commands::{
    AssigneeLoginsOptions, AutoLinkOptions, CloseOptions, ClosureHygieneOptions, CreateOptions,
    DoneStatusOptions, FetchNonComplianceReasonOptions, HasLabelOptions, IssueFieldOptions,
    IssueTarget, LabelExistsOptions, ListByLabelOptions, NeutralizeOptions,
    NonComplianceReasonOptions, OpenNumbersOptions, OpenSnapshotsOptions, ParentGuardOptions,
    ReadOptions, ReevaluateOptions, ReopenOnDevOptions, RequiredFieldsValidateOptions,
    StateOptions, SubissueRefsOptions, SyncProjectStatusOptions, TasklistRefsOptions,
    UpdateOptions, UpsertMarkerCommentOptions,
};

#[derive(Debug, Clone)]
pub(crate) enum IssueAction {
    Help,
    Create(CreateOptions),
    Read(ReadOptions),
    DoneStatus(DoneStatusOptions),
    ReopenOnDev(ReopenOnDevOptions),
    Update(UpdateOptions),
    RepoName,
    CurrentLogin,
    Close(CloseOptions),
    Reopen(IssueTarget),
    Delete(IssueTarget),
    Reevaluate(ReevaluateOptions),
    Neutralize(NeutralizeOptions),
    AutoLink(AutoLinkOptions),
    ParentGuard(ParentGuardOptions),
    ClosureHygiene(ClosureHygieneOptions),
    RequiredFieldsValidate(RequiredFieldsValidateOptions),
    NonComplianceReason(NonComplianceReasonOptions),
    FetchNonComplianceReason(FetchNonComplianceReasonOptions),
    LabelExists(LabelExistsOptions),
    SyncProjectStatus(SyncProjectStatusOptions),
    TasklistRefs(TasklistRefsOptions),
    SubissueRefs(SubissueRefsOptions),
    UpsertMarkerComment(UpsertMarkerCommentOptions),
    OpenNumbers(OpenNumbersOptions),
    OpenSnapshots(OpenSnapshotsOptions),
    AssigneeLogins(AssigneeLoginsOptions),
    State(StateOptions),
    HasLabel(HasLabelOptions),
    ListByLabel(ListByLabelOptions),
    Field(IssueFieldOptions),
}
