use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum ViolationCode {
    StructInvalidWorkspaceMembers,
    StructMissingBackendOrUi,
    StructThirdCrateDetected,
    StructForbiddenFolderName,
    StructMissingReadme,
    CrateNotBinOnly,
    CrateMissingMain,
    CrateBinaryMainUnscopedPub,
    CrateBinaryMainContainsStruct,
    CrateBinaryMainContainsEnum,
    CrateBinaryMainContainsTrait,
    CrateBinaryMainContainsImpl,
    CrateBinaryMainContainsNonEntrypointFn,
    CrateContainsLocalUseStatement,
    CrateContainsInlineTestAttribute,
    CrateMissingPairedTestFile,
    CratePairedTestNotUnitStyle,
    CratePrimaryItemContractViolation,
    CrateForbiddenSerdeJsonDependency,
    NameProductMismatch,
    NameCrateMismatch,
    LayerUiImportsBackend,
    LayerUiSuspectDomainLogic,
    LayerLibraryDependsOnHigherLayer,
    DetWallClockUsage,
    DetForbiddenTimeDep,
    DetStdoutUsage,
    DetStdioUsage,
    DetNondeterministicRngHeuristic,
    DetUnwrapRisk,
    DetPanicRisk,
    DetUnsafeUsage,
    DetUnderscoreUnusedMasking,
    StructMissingProductMetadata,
    StructMissingCrateManifest,
    StructShellRunMissingStrictMode,
    StructShellRunMissingSource,
    StructShellRunMissingEntrypoint,
    StructShellRunHasFunctionDefinition,
    StructShellLoadHasFunctionDefinition,
    StructShellLoadHasExecutableLogic,
    StructShellLoadInvalidConstantName,
    LayerLibraryHasMainRs,
    LayerLibraryMissingLibRs,
    RuleFileReadError,
}
