// projects/products/core/launcher/src/lib.rs
pub mod build;
pub mod cargo_commands;
pub mod child_handle;
pub mod ci;
pub mod config;
pub mod defaults;
pub mod entry;
pub mod launcher;
pub mod logging;
pub mod normalizer;
pub mod parsing;
pub mod process;
pub mod restart_policy;
pub mod service;
pub mod shutdown;
pub mod supervisor;
pub mod workspace;

pub(crate) use build::Build;
pub(crate) use cargo_commands::cargo_build;
pub(crate) use child_handle::ChildHandle;
pub(crate) use ci::Cli;
pub(crate) use config::Config;
pub(crate) use defaults::default_profile;
pub(crate) use entry::Paths;
pub(crate) use launcher::Launcher;
pub(crate) use logging::log_message;
pub(crate) use normalizer::normalize_path;
pub(crate) use parsing::parse_csv;
pub(crate) use process::{resolve_bin_path, spawn_service};
pub(crate) use restart_policy::{RestartPolicy, default_backoff, default_restart};
pub(crate) use service::{Service, topo_sort, validate_services};
pub(crate) use shutdown::install_shutdown_handler;
pub(crate) use supervisor::start_and_supervise;
pub(crate) use workspace::Workspace;
