use crate::spec::spec::RuntimeSpec;

pub struct ProjectEmitter;

impl ProjectEmitter {
    pub fn new() -> Self {
        Self
    }

    pub fn emit(&self, spec: &RuntimeSpec) -> Vec<(String, Vec<u8>)> {
        let mut artifacts = Vec::new();
        artifacts.push(("Cargo.toml".to_string(), self.emit_cargo_toml()));
        artifacts.push(("README.md".to_string(), self.emit_readme(spec)));
        artifacts
    }

    fn emit_cargo_toml(&self) -> Vec<u8> {
        let content = r#"[package]
name = "generated-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
"#;
        content.as_bytes().to_vec()
    }

    fn emit_readme(&self, spec: &RuntimeSpec) -> Vec<u8> {
        let mut out = String::new();
        out.push_str("# Generated Runtime\n\n");
        out.push_str("This project was generated by `spec_to_runtime_compiler`.\n\n");
        out.push_str("## States\n\n");
        for state in &spec.states {
            out.push_str(&format!("- **{}**", state.name));
            if !state.fields.is_empty() {
                let fields: Vec<String> = state
                    .fields
                    .iter()
                    .map(|f| format!("{}: {}", f.name, f.ty))
                    .collect();
                out.push_str(&format!(" ({})", fields.join(", ")));
            }
            out.push('\n');
        }
        out.push_str("\n## Transitions\n\n");
        for t in &spec.transitions {
            out.push_str(&format!("- {} → {} on `{}`\n", t.from, t.to, t.event));
        }
        out.push_str("\n## Invariants\n\n");
        for inv in &spec.invariants {
            out.push_str(&format!("- **{}**: {}\n", inv.name, inv.description));
        }
        out.into_bytes()
    }
}
