//! tools/versioning_automation/src/automation/commands/mod.rs
mod audit_issue_status_options;
mod audit_security_options;
mod automation_action;
mod build_accounts_ui_options;
mod build_and_check_ui_bundles_options;
mod build_ui_bundles_options;
mod changed_crates_options;
mod check_dependencies_options;
mod check_merge_conflicts_options;
mod check_priority_issues_options;
mod ci_watch_pr_options;
mod clean_artifacts_options;
mod commit_msg_check_options;
mod install_hooks_options;
mod labels_sync_options;
mod post_checkout_check_options;
mod pre_add_review_options;
mod pre_branch_create_check_options;
mod pre_commit_check_options;
mod pre_push_check_options;
mod prepare_commit_msg_options;
mod release_prepare_options;
mod sync_main_dev_ci_options;
mod test_coverage_options;

pub(crate) use audit_issue_status_options::AuditIssueStatusOptions;
pub(crate) use audit_security_options::AuditSecurityOptions;
pub(crate) use automation_action::AutomationAction;
pub(crate) use build_accounts_ui_options::BuildAccountsUiOptions;
pub(crate) use build_and_check_ui_bundles_options::BuildAndCheckUiBundlesOptions;
pub(crate) use build_ui_bundles_options::BuildUiBundlesOptions;
pub(crate) use changed_crates_options::ChangedCratesOptions;
pub(crate) use check_dependencies_options::CheckDependenciesOptions;
pub(crate) use check_merge_conflicts_options::CheckMergeConflictsOptions;
pub(crate) use check_priority_issues_options::CheckPriorityIssuesOptions;
pub(crate) use ci_watch_pr_options::CiWatchPrOptions;
pub(crate) use clean_artifacts_options::CleanArtifactsOptions;
pub(crate) use commit_msg_check_options::CommitMsgCheckOptions;
pub(crate) use install_hooks_options::InstallHooksOptions;
pub(crate) use labels_sync_options::LabelsSyncOptions;
pub(crate) use post_checkout_check_options::PostCheckoutCheckOptions;
pub(crate) use pre_add_review_options::PreAddReviewOptions;
pub(crate) use pre_branch_create_check_options::PreBranchCreateCheckOptions;
pub(crate) use pre_commit_check_options::PreCommitCheckOptions;
pub(crate) use pre_push_check_options::PrePushCheckOptions;
pub(crate) use prepare_commit_msg_options::PrepareCommitMsgOptions;
pub(crate) use release_prepare_options::ReleasePrepareOptions;
pub(crate) use sync_main_dev_ci_options::SyncMainDevCiOptions;
pub(crate) use test_coverage_options::TestCoverageOptions;
