//! projects/products/unstable/autonomous_dev_ai/src/lifecycle/mod.rs
// Lifecycle module surface (no business logic here).
mod action_boundary;
mod action_risk_level;
mod checkpoint;
mod circuit_breaker;
mod circuit_state;
mod compensation_kind;
mod execution_context;
mod iteration_manager;
mod iteration_number;
mod learning_context;
mod lifecycle_error;
mod lifecycle_manager;
mod lifecycle_metrics;
mod max_iterations;
mod metrics_collector;
mod metrics_inner;
mod process_usage;
mod resource_budget;
mod resource_type;
mod retry_strategy;
mod rollback_manager;
mod run_report;
mod step_index;
mod tool_metrics;
mod validation_command_plan;

pub(crate) use action_boundary::ActionBoundary;
pub(crate) use action_risk_level::ActionRiskLevel;
pub(crate) use checkpoint::Checkpoint;
pub(crate) use circuit_breaker::CircuitBreaker;
pub(crate) use circuit_state::CircuitState;
pub(crate) use compensation_kind::CompensationKind;
pub(crate) use execution_context::ExecutionContext;
pub(crate) use iteration_manager::IterationManager;
pub(crate) use iteration_number::IterationNumber;
pub(crate) use learning_context::LearningContext;
pub(crate) use lifecycle_error::{LifecycleError, LifecycleResult};
pub(crate) use lifecycle_manager::LifecycleManager;
pub(crate) use lifecycle_metrics::LifecycleMetrics;
pub(crate) use max_iterations::MaxIterations;
pub(crate) use metrics_collector::MetricsCollector;
pub(crate) use metrics_inner::MetricsInner;
pub(crate) use process_usage::ProcessUsage;
pub(crate) use resource_budget::ResourceBudget;
pub(crate) use resource_type::ResourceType;
pub(crate) use retry_strategy::RetryStrategy;
pub(crate) use rollback_manager::RollbackManager;
pub(crate) use run_report::RunReport;
pub(crate) use step_index::StepIndex;
pub(crate) use tool_metrics::ToolMetrics;
pub(crate) use validation_command_plan::ValidationCommandPlan;
