// projects/products/unstable/autonomous_dev_ai/src/lifecycle/mod.rs
// Lifecycle module surface (no business logic here).
mod action_boundary;
mod checkpoint;
mod circuit_breaker;
mod circuit_state;
mod compensation_kind;
mod execution_context;
mod iteration_number;
mod lifecycle_error;
mod lifecycle_manager;
mod lifecycle_metrics;
mod max_iterations;
mod metrics_collector;
mod metrics_inner;
mod resource_budget;
mod resource_type;
mod retry_strategy;
mod rollback_manager;
mod step_index;
mod tool_metrics;

pub use action_boundary::ActionBoundary;
pub use checkpoint::Checkpoint;
pub use circuit_breaker::CircuitBreaker;
pub use circuit_state::CircuitState;
pub use compensation_kind::CompensationKind;
pub use execution_context::ExecutionContext;
pub use iteration_number::IterationNumber;
pub use lifecycle_error::{LifecycleError, LifecycleResult};
pub use lifecycle_manager::LifecycleManager;
pub use lifecycle_metrics::LifecycleMetrics;
pub use max_iterations::MaxIterations;
pub use metrics_collector::MetricsCollector;
pub use metrics_inner::MetricsInner;
pub use resource_budget::ResourceBudget;
pub use resource_type::ResourceType;
pub use retry_strategy::RetryStrategy;
pub use rollback_manager::RollbackManager;
pub use step_index::StepIndex;
pub use tool_metrics::ToolMetrics;
