//! projects/products/varina/backend/src/autopilot/autopilot_plan.rs
use serde::{Deserialize, Serialize};

/// Structure representing an action plan generated by the autopilot.
/// Contains the necessary information to decide whether to apply changes.
/// Action plan (what the autopilot would do).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AutopilotPlan {
    pub branch: String,
    pub will_stage: Vec<String>,
    pub will_commit: bool,
    pub commit_message: String,
    pub will_push: bool,
    pub notes: Vec<String>,
}

impl AutopilotPlan {
    /// Validate the plan to ensure all fields are properly set.
    pub fn validate(&self) -> Result<(), String> {
        if self.branch.is_empty() {
            return Err("Branch name cannot be empty".to_string());
        }
        if self.commit_message.is_empty() {
            return Err("Commit message cannot be empty".to_string());
        }
        Ok(())
    }
}
