//! projects/products/varina/backend/src/autopilot/autopilot_plan.rs
use serde::{Deserialize, Serialize};

/// Structure representing an action plan generated by the autopilot.
/// Contains the necessary information to decide whether to apply changes.
/// Action plan (what the autopilot would do).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AutopilotPlan {
    pub branch: String,
    pub will_stage: Vec<String>,
    pub will_commit: bool,
    pub commit_message: String,
    pub will_push: bool,
    pub notes: Vec<String>,
}

impl AutopilotPlan {
    /// Validate the plan to ensure all fields are properly set.
    pub fn validate(&self) -> Result<(), String> {
        if self.branch.is_empty() {
            return Err("Branch name cannot be empty".to_string());
        }
        if self.commit_message.is_empty() {
            return Err("Commit message cannot be empty".to_string());
        }
        Ok(())
    }
}

#[test]
fn test_autopilot_plan_usage() {
    use crate::tests::test_helpers::AutopilotPlanBuilder;
    let plan = AutopilotPlanBuilder::new()
        .branch("main")
        .will_stage(vec!["file1.rs".to_string()])
        .will_commit(true)
        .commit_message("Initial commit")
        .will_push(true)
        .notes(vec!["Note 1".to_string()])
        .build();

    assert_eq!(plan.branch, "main");
    assert!(plan.will_commit);
    assert_eq!(plan.commit_message, "Initial commit");
    assert!(plan.will_push);
    assert_eq!(plan.notes.len(), 1);
}
#[test]
fn test_autopilot_plan_validation() {
    use crate::tests::test_helpers::AutopilotPlanBuilder;
    let mut plan = AutopilotPlanBuilder::new()
        .branch("")
        .will_commit(true)
        .commit_message("")
        .will_push(true)
        .build();

    assert_eq!(
        plan.validate().err(),
        Some("Branch name cannot be empty".to_string())
    );

    plan.branch = "main".to_string();
    assert_eq!(
        plan.validate().err(),
        Some("Commit message cannot be empty".to_string())
    );

    plan.commit_message = "Initial commit".to_string();
    assert!(plan.validate().is_ok());
}
